s:+ABBR:%<abbr%>:
s:+Abe:%<abe%>:
s:+Abl:%<abl%>:
s:+Acc:%<acc%>:
s:+ACR:%<acr%>:
s:+Act:%<act%>:
s:+AdA:%<adv%>:
s:+Adc:%<adc%>:
s:+Ade:%<ade%>:
s:+Adp:%<adp%>:
s:+Adv:%<adv%>:
s:+All:%<all%>:
s:+Apr::
s:+Attr::
s:+Bahuv::
s:+Card:%<card%>:
s:+CC:%<cnjcoo%>:
s:+CLB::
s:+Clt/bo:%<enc%>:
s:+Clt/gi:%<enc%>:
s:+Clt/hAi:%<enc%>:
s:+CmpN/xxx:%<cmp%>:
s:+Com:%<com%>:
s:+Comp:%<comp%>:
s:+Cond:%<cni%>:
s:+Conj:%<cnv%>:
s:+ConNeg:%<conneg%>:
s:+ConNegII:%<conneg%>:
s:+CS:%<cnjsub%>:
s:+Dat:%<dat%>:
s:+Dem:%<dem%>:
s:+Dep:%<dep%>:
s:+Der/A::
s:+Der/IA::
s:+Der/mA::
s:+Der/mbi::
s:+Der/mine::
s:+Der/Rc::
s:+Der/Ta::
s:+Der/Te::
s:+Der/Tu::
s:+Der/Us::
s:+Der/xxx::
s:+Egr:%<egr%>:
s:+Ela:%<ela%>:
s:+Err/Orth::
s:+Ess:%<ess%>:
s:+Foc:%<enc%>:
s:+Gen:%<gen%>:
s:+Ger:%<ger%>:
s:+Guess::
s:+Ill:%<ill%>:
s:+Imprt:%<imp%>:
s:+ImprtII:%<imp%>:
s:+Ind:%<pri%>:
s:+Indef:%<ind%>:
s:+Ind+Prs+ScSg3:%<pri%>%<p3%>%<sg%>:
s:+Ine:%<ine%>:
s:+Inf:%<inf%>:
s:+Ins:%<ins%>:
s:+Interj:%<ij%>:
s:+Interr:%<itg%>:
s:+Iter::
s:+IV::
s:+LEFT::
s:+Loc:%<loc%>:
s:+Multi:%<mul%>:
s:+Neg:%<neg%>:
s:+Nom:%<nom%>:
s:+Nom+Sg:%<nom%>%<sg%>:
s:+Num:%<num%>:
s:+Ord:%<ord%>:
s:+Ord+TYÄ:%<ord%>:
s:+Par:%<par%>:
s:+Pcle:%<part%>:
s:+Pers:%<prs%>:
s:+Pl1:%<p1%>%<pl%>:
s:+Pl2:%<p2%>%<pl%>:
s:+Pl3:%<p3%>%<pl%>:
s:+Pl:%<pl%>:
s:+Po:%<post%>:
s:+Po+Der/A:%<post%>%<adj%>:
s:+Pos:%<pos%>:
s:+Pot:%<pot%>:
s:+PrfPrc:%<pp%>:
s:+PrfPrcPl3:%<pp%>%<p3%>%<pl%>:
s:+Prl:%<prl%>:
s:+Pron:%<prn%>:
s:+Prop:%<np%>:
s:+Pros:%<pros%>:
s:+Prs+Pl3:%<pri%>%<p3%>%<pl%>:
s:+PrsPrc:%<pprs%>:
s:+Prs:%<pri%>:
s:+Prt:%<past%>:
s:+Pr:%<pr%>:
s:+Pss:%<pass%>:
s:+PUNCT:%<punct%>:
s:+PxDu1:%<px1du%>:
s:+PxDu2:%<px2du%>:
s:+PxDu3:%<px3du%>:
s:+PxPl1:%<px1pl%>:
s:+PxPl2:%<px2pl%>:
s:+PxPl3:%<px3pl%>:
s:+PxSg1:%<px1sg%>:
s:+PxSg2:%<px2sg%>:
s:+PxSg3:%<px3sg%>:
s:+PxSP3:%<px3sp%>:
s:+Qnt:%<ind%>:
s:+Qst:%<qu%>:
s:+RcPl:%<recip%>%<pl%>:
s:+RcPl1:%<recip%>%<p1>%<pl%>:
s:+RcPl2:%<recip%>%<p2>%<pl%>:
s:+RcPl3:%<recip%>%<p3>%<pl%>:
s:+RcPrfPrc:%<recip%>%<pp%>:
s:+RcSg:%<recip%>%<pl%>:
s:+RcSg1:%<recip%>%<p1>%<sg%>:
s:+RcSg2:%<recip%>%<p2>%<sg%>:
s:+RcSg3:%<recip%>%<p3>%<sg%>:
s:+Rc:%<recip%>:
s:+Recipr:%<recip%>:
s:+Refl:%<refl%>:
s:+Rel:%<rel%>:
s:+RIGHT::
s:+ScPl1:%<p1%>%<pl%>:
s:+ScPl2:%<p2%>%<pl%>:
s:+ScPl3:%<p3%>%<pl%>:
s:+ScSg1:%<p1%>%<sg%>:
s:+ScSg2:%<p2%>%<sg%>:
s:+ScSg3:%<p3%>%<sg%>:
s:+Sc::
s:+Sem/Wthr::
s:+Sem/Wpn::
s:+Sem/Veh::
s:+Sem/Txt::
s:+Sem/Tool-write::
s:+Sem/Tool-music::
s:+Sem/Tool-measr::
s:+Sem/Tool-it::
s:+Sem/Tool-clean::
s:+Sem/Tool-catch::
s:+Sem/Tool::
s:+Sem/Time_Wthr::
s:+Sem/Time::
s:+Sem/Symbol::
s:+Sem/Sur::
s:+Sem/Substnc_Wthr::
s:+Sem/Substnc::
s:+Sem/State-sick::
s:+Sem/State::
s:+Sem/Sport::
s:+Sem/Sign::
s:+Sem/Semcon_Txt::
s:+Sem/Semcon::
s:+Sem/Rvr::
s:+Sem/Rule::
s:+Sem/Route::
s:+Sem/Rel::
s:+Sem/Prod-vis::
s:+Sem/Prod-ling::
s:+Sem/Prod-cogn_Txt::
s:+Sem/Prod-cogn::
s:+Sem/Prod-audio_Txt::
s:+Sem/Prod-audio::
s:+Sem/Prod::
s:+Sem/Process::
s:+Sem/Pos::
s:+Sem/Plc_Wthr::
s:+Sem/Plc-water::
s:+Sem/Plc_Tool-catch::
s:+Sem/Plc_Time::
s:+Sem/Plc_Substnc_Wthr::
s:+Sem/Plc_Substnc::
s:+Sem/Plc_Route::
s:+Sem/Plc_Pos::
s:+Sem/Plc-line::
s:+Sem/Plc-elevate::
s:+Sem/Plc-abstr_Route::
s:+Sem/Plc-abstr_Rel_State::
s:+Sem/Plc-abstr::
s:+Sem/Plc::
s:+Sem/Plant_Tool-measr::
s:+Sem/Plant_Tool::
s:+Sem/Plant_Plant-part::
s:+Sem/Plant-part::
s:+Sem/Plant::
s:+Sem/Perc-psych::
s:+Sem/Perc-phys::
s:+Sem/Perc-emo_Wthr::
s:+Sem/Perc-emo::
s:+Sem/Perc-cogn::
s:+Sem/Patr::
s:+Sem/Part_Prod-cogn::
s:+Sem/Part::
s:+Sem/Org_Veh::
s:+Sem/Org_Txt::
s:+Sem/Org_Rule::
s:+Sem/Org::
s:+Sem/Obj-surfc::
s:+Sem/Obj_State::
s:+Sem/Obj_Semcon::
s:+Sem/Obj-rope::
s:+Sem/Obj-play_Sport::
s:+Sem/Obj-play::
s:+Sem/Obj-ling::
s:+Sem/Obj-el::
s:+Sem/Obj-cogn::
s:+Sem/Obj-clo::
s:+Sem/Obj::
s:+Sem/NonHum::
s:+Sem/Money_Txt::
s:+Sem/Money_Obj::
s:+Sem/Money::
s:+Sem/Measr_Time::
s:+Sem/Measr::
s:+Sem/Mat_Txt::
s:+Sem/Mat_Plant::
s:+Sem/Mat::
s:+Sem/Mal::
s:+Sem/Lang_Tool::
s:+Sem/Lang::
s:+Sem/Kin	::
s:+Sem/Kin::
s:+Sem/Inanim::
s:+Sem/Ideol::
s:+Sem/Hum_Wthr::
s:+Sem/Hum_Veh::
s:+Sem/Hum_Tool::
s:+Sem/Hum_Plc::
s:+Sem/Hum_Plant::
s:+Sem/Hum_Org::
s:+Sem/Hum_Obj::
s:+Sem/Hum_Lang_Time::
s:+Sem/Hum_Lang_Plc::
s:+Sem/Hum_Lang::
s:+Sem/Hum-abstr::
s:+Sem/Hum::
s:+Sem/Group_Txt::
s:+Sem/Group_Sign::
s:+Sem/Group_Org::
s:+Sem/Group_Hum_Prod-vis::
s:+Sem/Group_Hum_Plc::
s:+Sem/Group_Hum_Org::
s:+Sem/Group_Hum::
s:+Sem/Group::
s:+Sem/Geom_Obj::
s:+Sem/Geom::
s:+Sem/Game_Obj-play::
s:+Sem/Game::
s:+Sem/Furn::
s:+Sem/Food_Plant::
s:+Sem/Food_Perc-phys::
s:+Sem/Food-med::
s:+Sem/Food::
s:+Sem/Fem::
s:+Sem/Feat-psych_Hum::
s:+Sem/Feat-psych::
s:+Sem/Feat_Plant::
s:+Sem/Feat-phys_Wthr::
s:+Sem/Feat-phys_Veh::
s:+Sem/Feat-phys_Tool-write::
s:+Sem/Feat-phys::
s:+Sem/Feat-measr::
s:+Sem/Feat::
s:+Sem/Event_Time::
s:+Sem/Event_Plc::
s:+Sem/Event_Hum::
s:+Sem/Event_Food::
s:+Sem/Event::
s:+Sem/Edu_Org::
s:+Sem/Edu_Mat::
s:+Sem/Edu_Group_Hum::
s:+Sem/Edu_Event::
s:+Sem/Edu::
s:+Sem/Dummytag::
s:+Sem/Drink::
s:+Sem/Domain_Prod-audio::
s:+Sem/Domain_Food-med::
s:+Sem/Domain::
s:+Sem/Divinity::
s:+Sem/Dir::
s:+Sem/Dance_Prod-audio::
s:+Sem/Dance_Org::
s:+Sem/Dance::
s:+Sem/Curr_Org::
s:+Sem/Curr::
s:+Sem/Ctain_Tool-measr::
s:+Sem/Ctain_Tool::
s:+Sem/Ctain_Furn::
s:+Sem/Ctain_Feat-phys::
s:+Sem/Ctain-clth_Veh::
s:+Sem/Ctain-clth_Plant::
s:+Sem/Ctain-clth::
s:+Sem/Ctain-abstr_Org::
s:+Sem/Ctain-abstr::
s:+Sem/Ctain::
s:+Sem/Constellation::
s:+Sem/Color::
s:+Sem/Clth-part::
s:+Sem/Clth-jewl_Plant::
s:+Sem/Clth-jewl_Org::
s:+Sem/Clth-jewl_Money::
s:+Sem/Clth-jewl_Curr::
s:+Sem/Clth-jewl::
s:+Sem/Clth_Hum::
s:+Sem/Clth::
s:+Sem/Cat::
s:+Sem/Build_Route::
s:+Sem/Build-part_Plc::
s:+Sem/Build-part::
s:+Sem/Build_Org::
s:+Sem/Build_Event_Org::
s:+Sem/Build_Edu_Org::
s:+Sem/Build_Clth-part::
s:+Sem/Build_Build-part::
s:+Sem/Build::
s:+Sem/Body_Time::
s:+Sem/Body_Plc::
s:+Sem/Body_Obj_Tool-catch::
s:+Sem/Body_Measr::
s:+Sem/Body_Mat::
s:+Sem/Body_Hum::
s:+Sem/Body_Group_Hum::
s:+Sem/Body_Food::
s:+Sem/Body_Clth::
s:+Sem/Body_Body-abstr::
s:+Sem/Body-abstr_Prod-audio_Semcon::
s:+Sem/Body-abstr::
s:+Sem/Body::
s:+Sem/Ant_Mal:%<ant%>%<m%>:
s:+Sem/Ant_Fem:%<ant%>%<f%>:
s:+Sem/Ant:%<ant%>:
s:+Sem/Ani_Veh::
s:+Sem/Ani_Time::
s:+Sem/Aniprod_Plc::
s:+Sem/Aniprod_Perc-phys::
s:+Sem/Aniprod_Obj-clo::
s:+Sem/Aniprod_Hum::
s:+Sem/Aniprod::
s:+Sem/Ani_Plc_Txt::
s:+Sem/Ani_Plc::
s:+Sem/Ani_Hum_Time::
s:+Sem/Ani_Hum_Plc::
s:+Sem/Ani_Hum::
s:+Sem/Ani_Group_Hum::
s:+Sem/Ani_Group::
s:+Sem/Ani_Build-part::
s:+Sem/Ani_Build_Hum_Txt::
s:+Sem/Ani_Build::
s:+Sem/Ani_Body-abstr_Hum::
s:+Sem/Ani::
s:+Sem/Amount_Semcon::
s:+Sem/Amount_Build::
s:+Sem/Amount::
s:+Sem/Act_Route::
s:+Sem/Act_Plc::
s:+Sem/Act_Group::
s:+Sem/Act::
s:+Sg1:%<p1%>%<sg%>:
s:+Sg2:%<p2%>%<sg%>:
s:+Sg3:%<p3%>%<sg%>:
s:+Sg:%<sg%>:
s:+Spat::
s:+Sup:%<sup%>:
s:+Superl:%<sup%>:
s:+Symbol:%<sym%>:
s:+Temp:%<temp%>:
s:+Ter:%<term%>:
s:+Tra:%<tra%>:
s:+TV::
s:+TYÄ:%<FIXME%>:
s:+Use/Circ:+%<cmp%>:
s:+Use/CircN:+%<cmp%>:
s:+Use/Marg::
s:+Use/NG::
s:+Use/-Spell::
s:+Use/SpellNoSugg::
s:+V:%<vblex%>:
s:+V→A:%<adj%>:
s:+VAbess:%<abe%>:
s:+VGen:%<gen%>:
s:+V→N:%<n%>:
s:+V→V:%<vblex%>:
s:+A:%<adj%>:
s:+N:%<n%>:
